name: Create Tag

on:
  pull_request:
    types: [closed]
    branches: [develop, stage]

permissions:
  contents: write

env:
  HUSKY: 0
  TAG_NAME: ${{ github.ref_name }}

jobs:
  create-tag:
    name: Auto-create tag from merged branch
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/stage')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug
        run: |
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "head: ${{ github.head_ref }}"
          echo "base: ${{ github.base_ref }}"
          echo "action: ${{ github.event.action }}"
